substitutions:
  device_name: langji-ac
  friendly_name: Langji AC Controller
  wifi_ssid: "YOUR_WIFI_SSID"
  wifi_password: "YOUR_WIFI_PASSWORD"
  modbus_address: "0x01"

esphome:
  name: ${device_name}
  comment: "ESPHome configuration for Langji AC via Modbus RTU"
  project:
    name: langji.ac_controller
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Configure the UART bus for RS485/Modbus
uart:
  id: modbus_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: modbus_bus

modbus_controller:
  - id: langji_modbus
    address: ${modbus_address}
    modbus_id: modbus_bus
    command_throttle: 200ms
    setup_priority: -10
    update_interval: 10s

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${friendly_name} Fallback"
    password: "12345678"

logger:
api:
ota:
  platform: esphome

switch:
  # Write Single Coil (0x05): remote power control
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Power"
    register_type: coil
    address: 0x0000
    icon: mdi:power
  # Optional: start self-check routine
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Self Check"
    register_type: coil
    address: 0x0001
    icon: mdi:stethoscope
    entity_category: diagnostic
  # Force cooling/heating modes
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Force Cooling"
    register_type: coil
    address: 0x0004
    icon: mdi:snowflake-alert
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Force Heating"
    register_type: coil
    address: 0x0005
    icon: mdi:fire
  # Hydrogen discharge toggle
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Hydrogen Discharge"
    register_type: coil
    address: 0x0007
    icon: mdi:weather-windy
  # Alarm reset
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Reset Alarm"
    register_type: coil
    address: 0x000B
    icon: mdi:bell-cancel

binary_sensor:
  # Coil register states (0x01)
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Running"
    register_type: coil
    address: 0x0000
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Self-Check Running"
    register_type: coil
    address: 0x0001
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Cooling"
    register_type: coil
    address: 0x0002
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Heating"
    register_type: coil
    address: 0x0003
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Internal Fan"
    register_type: coil
    address: 0x0004
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} External Fan"
    register_type: coil
    address: 0x0005
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Dehumidifying"
    register_type: coil
    address: 0x0006
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Hydrogen Discharging"
    register_type: coil
    address: 0x0007
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Dry Contact Alarm"
    register_type: coil
    address: 0x0009

  # Discrete input alarms/faults (0x02)
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Return Air Sensor Fault"
    register_type: discrete_input
    address: 0x0000
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Condenser Sensor Fault"
    register_type: discrete_input
    address: 0x0001
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Outdoor Sensor Fault"
    register_type: discrete_input
    address: 0x0002
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Indoor Humidity Sensor Fault"
    register_type: discrete_input
    address: 0x0003
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Compressor Underload"
    register_type: discrete_input
    address: 0x0004
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Compressor Overload"
    register_type: discrete_input
    address: 0x0005
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Heater Underload"
    register_type: discrete_input
    address: 0x0006
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Heater Overload"
    register_type: discrete_input
    address: 0x0007
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Internal Fan Alarm"
    register_type: discrete_input
    address: 0x0008
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} External Fan Alarm"
    register_type: discrete_input
    address: 0x0009
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} High Pressure Alarm"
    register_type: discrete_input
    address: 0x000A
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Low Pressure Alarm"
    register_type: discrete_input
    address: 0x000B
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Inside High Temp Alarm"
    register_type: discrete_input
    address: 0x000C
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Inside Low Temp Alarm"
    register_type: discrete_input
    address: 0x000D
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Outside High Temp Alarm"
    register_type: discrete_input
    address: 0x000E
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Outside Low Temp Alarm"
    register_type: discrete_input
    address: 0x000F
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} External Input Alarm"
    register_type: discrete_input
    address: 0x0011
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Evaporator Sensor Fault"
    register_type: discrete_input
    address: 0x0014
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} High Humidity Alarm"
    register_type: discrete_input
    address: 0x0015
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Low Voltage Alarm"
    register_type: discrete_input
    address: 0x0016
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} High Voltage Alarm"
    register_type: discrete_input
    address: 0x0017
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Inverter Compressor Fault"
    register_type: discrete_input
    address: 0x0018
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Evaporator Freezing Alarm"
    register_type: discrete_input
    address: 0x001B
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Frequent High Pressure"
    register_type: discrete_input
    address: 0x001C
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Frequent Low Pressure"
    register_type: discrete_input
    address: 0x001D
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} High Condenser Temp"
    register_type: discrete_input
    address: 0x001E
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Refrigerant Leak"
    register_type: discrete_input
    address: 0x001F
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Compressor Comm Fault"
    register_type: discrete_input
    address: 0x0020
    entity_category: diagnostic

sensor:
  # Input registers (0x04)
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Return Air Temperature"
    register_type: read
    address: 0x0000
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Condenser Temperature"
    register_type: read
    address: 0x0001
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Compressor/Heater Current"
    register_type: read
    address: 0x0002
    unit_of_measurement: "A"
    accuracy_decimals: 2
    value_type: U_WORD
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Internal Fan Current"
    register_type: read
    address: 0x0003
    unit_of_measurement: "A"
    accuracy_decimals: 2
    value_type: U_WORD
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} External Fan Current"
    register_type: read
    address: 0x0004
    unit_of_measurement: "A"
    accuracy_decimals: 2
    value_type: U_WORD
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} AC Voltage"
    register_type: read
    address: 0x0005
    unit_of_measurement: "V"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Outdoor Temperature"
    register_type: read
    address: 0x0006
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Indoor Humidity"
    register_type: read
    address: 0x0007
    unit_of_measurement: "%"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Evaporator Temperature"
    register_type: read
    address: 0x0008
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Internal Fan Speed"
    register_type: read
    address: 0x0009
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} External Fan Speed"
    register_type: read
    address: 0x000A
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Compressor Speed"
    register_type: read
    address: 0x000B
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    value_type: U_WORD

number:
  # Holding registers (0x03/0x06/0x10)
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Compressor Start Temp"
    register_type: holding
    address: 0x0000
    unit_of_measurement: "°C"
    value_type: S_WORD
    min_value: -40
    max_value: 120
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (int16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Compressor Stop Delta"
    register_type: holding
    address: 0x0001
    unit_of_measurement: "°C"
    value_type: S_WORD
    min_value: 0
    max_value: 30
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (int16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Heater Start Temp"
    register_type: holding
    address: 0x0002
    unit_of_measurement: "°C"
    value_type: S_WORD
    min_value: -40
    max_value: 120
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (int16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Heater Stop Delta"
    register_type: holding
    address: 0x0003
    unit_of_measurement: "°C"
    value_type: S_WORD
    min_value: 0
    max_value: 30
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (int16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Cabinet High Temp Limit"
    register_type: holding
    address: 0x0004
    unit_of_measurement: "°C"
    value_type: S_WORD
    min_value: 0
    max_value: 100
    step: 0.1
    mode: box
    lambda: return x / 100.0;
    write_lambda: return (int16_t) (x * 100.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Cabinet Low Temp Limit"
    register_type: holding
    address: 0x0005
    unit_of_measurement: "°C"
    value_type: S_WORD
    min_value: -40
    max_value: 120
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (int16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Dehumidify Start Humidity"
    register_type: holding
    address: 0x0006
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (uint16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Dehumidify Stop Delta"
    register_type: holding
    address: 0x0007
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 50
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (uint16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} High Humidity Alarm"
    register_type: holding
    address: 0x0008
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (uint16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Dehumidification Enable"
    register_type: holding
    address: 0x0009
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 0.5
    mode: box
    lambda: return x / 10.0;
    write_lambda: return (uint16_t) (x * 10.0);
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Standby Internal Fan"
    register_type: holding
    address: 0x000D
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    mode: slider
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Communication Baud"
    register_type: holding
    address: 0x000E
    value_type: U_WORD
    min_value: 0
    max_value: 3
    step: 1
    mode: slider
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: langji_modbus
    name: "${friendly_name} Communication Address"
    register_type: holding
    address: 0x0014
    value_type: U_WORD
    min_value: 1
    max_value: 247
    step: 1
    mode: slider
    entity_category: diagnostic
